name: Deploy to VPS - Style D

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # Step 1: SSH Setup
      - name: Install SSH Private Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Add SSH Host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Step 2: Clean previous build
      - name: Clean Previous Build
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /home/autem-style-d/htdocs/style-d.autem.dev
            rm -rf .next
          "

      # Step 3: Git Operations
      - name: Pull Latest Code
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /home/autem-style-d/htdocs/style-d.autem.dev
            git pull origin main
          "

      # Step 4: Dependency Management
      - name: Install Dependencies with Bun
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            export PATH=\"/root/.bun/bin:\$PATH\"
            cd /home/autem-style-d/htdocs/style-d.autem.dev
            bun install
          "

      # Step 5: Build Project
      - name: Build Project
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            export PATH=\"/root/.bun/bin:\$PATH\"
            cd /home/autem-style-d/htdocs/style-d.autem.dev
            bun run build
          "

      # Step 6: PM2 Reload
      - name: Reload PM2 Process
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /home/autem-style-d/htdocs/style-d.autem.dev
            pm2 reload pm2.config.cjs --update-env
            pm2 save
          "

      # Step 7: Cleanup
      - name: Cleanup SSH Keys
        run: rm -rf ~/.ssh
