name: Deploy to VPS - Style D

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: /home/autem-style-d/htdocs/style-d.autem.dev
      SSH_CMD: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

    steps:
      # 1. Combined SSH setup
      - name: Configure SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # 2. Deployment commands
      - name: Clean build
        run: ${{ env.SSH_CMD }} "cd ${{ env.WORKING_DIR }} && rm -rf .next"

      - name: Git pull
        run: ${{ env.SSH_CMD }} "cd ${{ env.WORKING_DIR }} && git pull origin main"

      - name: Install & build
        run: ${{ env.SSH_CMD }} "cd ${{ env.WORKING_DIR }} && export PATH=\"/root/.bun/bin:\$PATH\" && bun install && bun run build"

      - name: PM2 reload
        run: ${{ env.SSH_CMD }} "cd ${{ env.WORKING_DIR }} && pm2 reload pm2.config.cjs --update-env && pm2 save"

      # 3. Cleanup
      - name: Remove SSH keys
        run: rm -rf ~/.ssh
